import { createContext, useContext, useState, useCallback, type ReactNode } from "react";

export type Language = "en" | "hi" | "kn" | "te" | "ta";

export const languageNames: Record<Language, string> = {
  en: "English",
  hi: "हिन्दी",
  kn: "ಕನ್ನಡ",
  te: "తెలుగు",
  ta: "தமிழ்",
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.upload": "Upload",
    "nav.environment": "Environment",
    "nav.history": "History",
    "nav.signIn": "Sign In",
    "nav.signOut": "Sign Out",

    // Hero
    "hero.badge": "AI-Powered Detection",
    "hero.title1": "Detect crop damage",
    "hero.title2": "before it spreads.",
    "hero.subtitle": "Upload a photo of your field or enter environmental data. Get instant AI analysis for animal damage, crop lodging, and smart recovery recommendations.",
    "hero.uploadBtn": "Upload Image",
    "hero.dataBtn": "Enter Data",

    // Features
    "features.heading": "How It Works",
    "features.subheading": "Simple, powerful tools designed for farmers",
    "features.imageDetection": "Image Detection",
    "features.imageDetectionDesc": "Upload photos for instant AI-powered crop damage analysis",
    "features.severityEstimation": "Severity Estimation",
    "features.severityEstimationDesc": "Get accurate damage severity levels from low to high",
    "features.smartRecommendations": "Smart Recommendations",
    "features.smartRecommendationsDesc": "Receive tailored recovery plans based on damage type",
    "features.riskAssessment": "Risk Assessment",
    "features.riskAssessmentDesc": "Enter environmental data for predictive damage analysis",

    // Image Upload
    "upload.heading": "Image Analysis",
    "upload.subheading": "Upload a clear photo of your crop to detect damage, estimate severity, and get recovery recommendations.",
    "upload.dropzone": "Upload Crop Image",
    "upload.formats": "JPG, PNG, JPEG — drag & drop or tap to select",
    "upload.selectBtn": "Select Photo",
    "upload.analyzing": "Analyzing your crop...",
    "upload.reAnalyze": "Re-Analyze",
    "upload.complete": "Analysis Complete",
    "upload.failed": "Analysis Failed",
    "upload.invalidFile": "Invalid file",
    "upload.invalidFileDesc": "Please upload an image file (JPG, PNG).",
    "upload.healthyCrops": "Healthy crops",

    // Environmental Form
    "env.heading": "Environmental Risk Assessment",
    "env.subheading": "Enter your field conditions to get a damage risk prediction and preventive recommendations.",
    "env.cropType": "Crop Type",
    "env.selectCrop": "Select crop",
    "env.wheat": "Wheat",
    "env.rice": "Rice",
    "env.corn": "Corn",
    "env.sugarcane": "Sugarcane",
    "env.cotton": "Cotton",
    "env.vegetables": "Vegetables",
    "env.rainfall": "Rainfall Level",
    "env.selectLevel": "Select level",
    "env.low": "Low",
    "env.moderate": "Moderate",
    "env.heavy": "Heavy",
    "env.wind": "Wind Exposure",
    "env.high": "High",
    "env.soil": "Soil Condition",
    "env.selectCondition": "Select condition",
    "env.good": "Good",
    "env.average": "Average",
    "env.poor": "Poor",
    "env.fieldSize": "Field Size (acres)",
    "env.analyzing": "Analyzing...",
    "env.predictRisk": "Predict Risk",

    // Result Card
    "result.severity": "Severity",
    "result.confidence": "Confidence",
    "result.areaAffected": "Area Affected",
    "result.recommendations": "Recovery Recommendations",

    // Damage labels
    "damage.safe": "No Damage Detected",
    "damage.animal_damage": "Animal Damage Detected",
    "damage.crop_lodging": "Crop Lodging Detected",
    "damage.combined": "Combined Damage Detected",

    // History
    "history.title": "Scan History",
    "history.scans": "scans",
    "history.scan": "scan",
    "history.clearAll": "Clear All",
    "history.noScans": "No scans yet",
    "history.noScansDesc": "Upload a crop image or enter environmental data to start.",
    "history.goToDashboard": "Go to Dashboard",
    "history.imageScan": "Image scan",
    "history.environmental": "Environmental",

    // Auth
    "auth.welcomeBack": "Welcome back",
    "auth.signInDesc": "Sign in to your account",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.forgotPassword": "Forgot password?",
    "auth.signInBtn": "Sign In",
    "auth.noAccount": "Don't have an account?",
    "auth.signUpLink": "Sign up",
    "auth.createAccount": "Create your account",
    "auth.createAccountDesc": "Start monitoring your crops today",
    "auth.fullName": "Full Name",
    "auth.createBtn": "Create Account",
    "auth.hasAccount": "Already have an account?",
    "auth.signInLink": "Sign in",
    "auth.resetTitle": "Reset your password",
    "auth.resetDesc": "We'll send you a link to reset it",
    "auth.checkEmail": "Check your email",
    "auth.resetSent": "We sent a password reset link to",
    "auth.sendResetLink": "Send Reset Link",
    "auth.backToLogin": "Back to login",
    "auth.setNewPassword": "Set new password",
    "auth.setNewPasswordDesc": "Enter your new password below",
    "auth.newPassword": "New Password",
    "auth.updatePassword": "Update Password",
    "auth.verifyingLink": "Verifying reset link...",
    "auth.accountCreated": "Account created!",
    "auth.checkEmailVerify": "Check your email for a verification link.",
    "auth.loginFailed": "Login failed",
    "auth.signupFailed": "Signup failed",
    "auth.passwordUpdated": "Password updated!",
    "auth.passwordUpdatedDesc": "You can now sign in with your new password.",

    // Footer
    "footer.text": "© 2026 CropGuard AI — Smart Crop Damage Detection",

    // Voice Assistant
    "voice.notSupported": "Speech not supported",
    "voice.notSupportedDesc": "Your browser does not support speech recognition.",
    "voice.heard": "I heard:",
    "voice.goingUpload": "Going to image upload section.",
    "voice.goingHistory": "Opening your scan history.",
    "voice.goingEnvironment": "Going to environmental data section.",
    "voice.noResult": "No analysis result yet. Please upload an image first.",
    "voice.notUnderstood": "Sorry, I didn't understand. Try saying upload image, show history, or analyze crop.",
    "voice.error": "Voice Error",
    "voice.stopReading": "Stop reading",
    "voice.readResult": "Read result aloud",
    "voice.startListening": "Start voice command",
    "voice.stopListening": "Stop listening",

    // General
    "previous": "previous",
  },
  hi: {
    "nav.upload": "अपलोड",
    "nav.environment": "पर्यावरण",
    "nav.history": "इतिहास",
    "nav.signIn": "साइन इन",
    "nav.signOut": "साइन आउट",
    "hero.badge": "AI-संचालित पहचान",
    "hero.title1": "फसल क्षति का पता लगाएं",
    "hero.title2": "फैलने से पहले।",
    "hero.subtitle": "अपने खेत की फोटो अपलोड करें या पर्यावरण डेटा दर्ज करें। पशु क्षति, फसल गिरने और स्मार्ट रिकवरी सिफारिशों के लिए तुरंत AI विश्लेषण प्राप्त करें।",
    "hero.uploadBtn": "छवि अपलोड करें",
    "hero.dataBtn": "डेटा दर्ज करें",
    "features.heading": "यह कैसे काम करता है",
    "features.subheading": "किसानों के लिए सरल, शक्तिशाली उपकरण",
    "features.imageDetection": "छवि पहचान",
    "features.imageDetectionDesc": "तुरंत AI-संचालित फसल क्षति विश्लेषण के लिए फोटो अपलोड करें",
    "features.severityEstimation": "गंभीरता अनुमान",
    "features.severityEstimationDesc": "कम से उच्च तक सटीक क्षति गंभीरता स्तर प्राप्त करें",
    "features.smartRecommendations": "स्मार्ट सिफारिशें",
    "features.smartRecommendationsDesc": "क्षति प्रकार के आधार पर अनुकूलित रिकवरी योजनाएं प्राप्त करें",
    "features.riskAssessment": "जोखिम मूल्यांकन",
    "features.riskAssessmentDesc": "पूर्वानुमानित क्षति विश्लेषण के लिए पर्यावरण डेटा दर्ज करें",
    "upload.heading": "छवि विश्लेषण",
    "upload.subheading": "क्षति का पता लगाने, गंभीरता का अनुमान लगाने और रिकवरी सिफारिशें प्राप्त करने के लिए अपनी फसल की स्पष्ट फोटो अपलोड करें।",
    "upload.dropzone": "फसल की छवि अपलोड करें",
    "upload.formats": "JPG, PNG, JPEG — खींचें और छोड़ें या चुनने के लिए टैप करें",
    "upload.selectBtn": "फोटो चुनें",
    "upload.analyzing": "आपकी फसल का विश्लेषण हो रहा है...",
    "upload.reAnalyze": "पुनः विश्लेषण",
    "upload.complete": "विश्लेषण पूर्ण",
    "upload.failed": "विश्लेषण विफल",
    "upload.invalidFile": "अमान्य फ़ाइल",
    "upload.invalidFileDesc": "कृपया एक छवि फ़ाइल (JPG, PNG) अपलोड करें।",
    "upload.healthyCrops": "स्वस्थ फसलें",
    "env.heading": "पर्यावरणीय जोखिम मूल्यांकन",
    "env.subheading": "क्षति जोखिम भविष्यवाणी और निवारक सिफारिशें प्राप्त करने के लिए अपने खेत की स्थिति दर्ज करें।",
    "env.cropType": "फसल प्रकार",
    "env.selectCrop": "फसल चुनें",
    "env.wheat": "गेहूं",
    "env.rice": "चावल",
    "env.corn": "मक्का",
    "env.sugarcane": "गन्ना",
    "env.cotton": "कपास",
    "env.vegetables": "सब्ज़ियाँ",
    "env.rainfall": "वर्षा स्तर",
    "env.selectLevel": "स्तर चुनें",
    "env.low": "कम",
    "env.moderate": "मध्यम",
    "env.heavy": "भारी",
    "env.wind": "हवा का जोखिम",
    "env.high": "उच्च",
    "env.soil": "मिट्टी की स्थिति",
    "env.selectCondition": "स्थिति चुनें",
    "env.good": "अच्छी",
    "env.average": "औसत",
    "env.poor": "खराब",
    "env.fieldSize": "खेत का आकार (एकड़)",
    "env.analyzing": "विश्लेषण हो रहा है...",
    "env.predictRisk": "जोखिम का अनुमान लगाएं",
    "result.severity": "गंभीरता",
    "result.confidence": "विश्वास",
    "result.areaAffected": "प्रभावित क्षेत्र",
    "result.recommendations": "रिकवरी सिफारिशें",
    "damage.safe": "कोई क्षति नहीं",
    "damage.animal_damage": "पशु क्षति पाई गई",
    "damage.crop_lodging": "फसल गिरना पाया गया",
    "damage.combined": "संयुक्त क्षति पाई गई",
    "history.title": "स्कैन इतिहास",
    "history.scans": "स्कैन",
    "history.scan": "स्कैन",
    "history.clearAll": "सब हटाएं",
    "history.noScans": "अभी तक कोई स्कैन नहीं",
    "history.noScansDesc": "शुरू करने के लिए फसल की छवि अपलोड करें या पर्यावरण डेटा दर्ज करें।",
    "history.goToDashboard": "डैशबोर्ड पर जाएं",
    "history.imageScan": "छवि स्कैन",
    "history.environmental": "पर्यावरणीय",
    "auth.welcomeBack": "वापस स्वागत है",
    "auth.signInDesc": "अपने खाते में साइन इन करें",
    "auth.email": "ईमेल",
    "auth.password": "पासवर्ड",
    "auth.forgotPassword": "पासवर्ड भूल गए?",
    "auth.signInBtn": "साइन इन",
    "auth.noAccount": "खाता नहीं है?",
    "auth.signUpLink": "साइन अप करें",
    "auth.createAccount": "अपना खाता बनाएं",
    "auth.createAccountDesc": "आज ही अपनी फसलों की निगरानी शुरू करें",
    "auth.fullName": "पूरा नाम",
    "auth.createBtn": "खाता बनाएं",
    "auth.hasAccount": "पहले से खाता है?",
    "auth.signInLink": "साइन इन करें",
    "auth.resetTitle": "अपना पासवर्ड रीसेट करें",
    "auth.resetDesc": "हम आपको रीसेट लिंक भेजेंगे",
    "auth.checkEmail": "अपना ईमेल जांचें",
    "auth.resetSent": "हमने पासवर्ड रीसेट लिंक भेजा है",
    "auth.sendResetLink": "रीसेट लिंक भेजें",
    "auth.backToLogin": "लॉगिन पर वापस जाएं",
    "auth.setNewPassword": "नया पासवर्ड सेट करें",
    "auth.setNewPasswordDesc": "नीचे अपना नया पासवर्ड दर्ज करें",
    "auth.newPassword": "नया पासवर्ड",
    "auth.updatePassword": "पासवर्ड अपडेट करें",
    "auth.verifyingLink": "रीसेट लिंक सत्यापित हो रहा है...",
    "auth.accountCreated": "खाता बनाया गया!",
    "auth.checkEmailVerify": "सत्यापन लिंक के लिए अपना ईमेल जांचें।",
    "auth.loginFailed": "लॉगिन विफल",
    "auth.signupFailed": "साइनअप विफल",
    "auth.passwordUpdated": "पासवर्ड अपडेट हुआ!",
    "auth.passwordUpdatedDesc": "अब आप अपने नए पासवर्ड से साइन इन कर सकते हैं।",
    "footer.text": "© 2026 CropGuard AI — स्मार्ट फसल क्षति पहचान",
    "voice.notSupported": "भाषण समर्थित नहीं",
    "voice.notSupportedDesc": "आपका ब्राउज़र भाषण पहचान का समर्थन नहीं करता।",
    "voice.heard": "मैंने सुना:",
    "voice.goingUpload": "छवि अपलोड अनुभाग पर जा रहे हैं।",
    "voice.goingHistory": "आपका स्कैन इतिहास खोल रहे हैं।",
    "voice.goingEnvironment": "पर्यावरण डेटा अनुभाग पर जा रहे हैं।",
    "voice.noResult": "अभी तक कोई विश्लेषण परिणाम नहीं। कृपया पहले एक छवि अपलोड करें।",
    "voice.notUnderstood": "क्षमा करें, मैं समझ नहीं पाया। अपलोड, इतिहास या विश्लेषण कहकर देखें।",
    "voice.error": "ध्वनि त्रुटि",
    "voice.stopReading": "पढ़ना बंद करें",
    "voice.readResult": "परिणाम पढ़ें",
    "voice.startListening": "ध्वनि आदेश शुरू करें",
    "voice.stopListening": "सुनना बंद करें",
    "previous": "पिछले",
  },
  kn: {
    "nav.upload": "ಅಪ್‌ಲೋಡ್",
    "nav.environment": "ಪರಿಸರ",
    "nav.history": "ಇತಿಹಾಸ",
    "nav.signIn": "ಸೈನ್ ಇನ್",
    "nav.signOut": "ಸೈನ್ ಔಟ್",
    "hero.badge": "AI-ಚಾಲಿತ ಪತ್ತೆ",
    "hero.title1": "ಬೆಳೆ ಹಾನಿಯನ್ನು ಪತ್ತೆ ಮಾಡಿ",
    "hero.title2": "ಹರಡುವ ಮೊದಲು.",
    "hero.subtitle": "ನಿಮ್ಮ ಹೊಲದ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಅಥವಾ ಪರಿಸರ ಡೇಟಾ ನಮೂದಿಸಿ. ಪ್ರಾಣಿ ಹಾನಿ, ಬೆಳೆ ಬೀಳುವಿಕೆ ಮತ್ತು ಚೇತರಿಕೆ ಶಿಫಾರಸುಗಳಿಗೆ ತಕ್ಷಣ AI ವಿಶ್ಲೇಷಣೆ ಪಡೆಯಿರಿ.",
    "hero.uploadBtn": "ಚಿತ್ರ ಅಪ್‌ಲೋಡ್",
    "hero.dataBtn": "ಡೇಟಾ ನಮೂದಿಸಿ",
    "features.heading": "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    "features.subheading": "ರೈತರಿಗಾಗಿ ಸರಳ, ಶಕ್ತಿಶಾಲಿ ಸಾಧನಗಳು",
    "features.imageDetection": "ಚಿತ್ರ ಪತ್ತೆ",
    "features.imageDetectionDesc": "ತಕ್ಷಣ AI ಬೆಳೆ ಹಾನಿ ವಿಶ್ಲೇಷಣೆಗೆ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    "features.severityEstimation": "ತೀವ್ರತೆ ಅಂದಾಜು",
    "features.severityEstimationDesc": "ಕಡಿಮೆಯಿಂದ ಹೆಚ್ಚಿನವರೆಗೆ ನಿಖರ ಹಾನಿ ತೀವ್ರತೆ ಮಟ್ಟ ಪಡೆಯಿರಿ",
    "features.smartRecommendations": "ಸ್ಮಾರ್ಟ್ ಶಿಫಾರಸುಗಳು",
    "features.smartRecommendationsDesc": "ಹಾನಿ ಪ್ರಕಾರದ ಆಧಾರದ ಮೇಲೆ ಚೇತರಿಕೆ ಯೋಜನೆಗಳನ್ನು ಪಡೆಯಿರಿ",
    "features.riskAssessment": "ಅಪಾಯ ಮೌಲ್ಯಮಾಪನ",
    "features.riskAssessmentDesc": "ಪೂರ್ವಾನುಮಾನ ಹಾನಿ ವಿಶ್ಲೇಷಣೆಗೆ ಪರಿಸರ ಡೇಟಾ ನಮೂದಿಸಿ",
    "upload.heading": "ಚಿತ್ರ ವಿಶ್ಲೇಷಣೆ",
    "upload.subheading": "ಹಾನಿ ಪತ್ತೆ, ತೀವ್ರತೆ ಅಂದಾಜು ಮತ್ತು ಚೇತರಿಕೆ ಶಿಫಾರಸುಗಳಿಗೆ ನಿಮ್ಮ ಬೆಳೆಯ ಸ್ಪಷ್ಟ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    "upload.dropzone": "ಬೆಳೆ ಚಿತ್ರ ಅಪ್‌ಲೋಡ್",
    "upload.formats": "JPG, PNG, JPEG — ಎಳೆದು ಬಿಡಿ ಅಥವಾ ಆಯ್ಕೆ ಮಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
    "upload.selectBtn": "ಫೋಟೋ ಆಯ್ಕೆ",
    "upload.analyzing": "ನಿಮ್ಮ ಬೆಳೆ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    "upload.reAnalyze": "ಮರು ವಿಶ್ಲೇಷಣೆ",
    "upload.complete": "ವಿಶ್ಲೇಷಣೆ ಪೂರ್ಣ",
    "upload.failed": "ವಿಶ್ಲೇಷಣೆ ವಿಫಲ",
    "upload.invalidFile": "ಅಮಾನ್ಯ ಫೈಲ್",
    "upload.invalidFileDesc": "ದಯವಿಟ್ಟು ಚಿತ್ರ ಫೈಲ್ (JPG, PNG) ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    "upload.healthyCrops": "ಆರೋಗ್ಯಕರ ಬೆಳೆಗಳು",
    "env.heading": "ಪರಿಸರ ಅಪಾಯ ಮೌಲ್ಯಮಾಪನ",
    "env.subheading": "ಹಾನಿ ಅಪಾಯ ಮುನ್ಸೂಚನೆ ಮತ್ತು ತಡೆಗಟ್ಟುವ ಶಿಫಾರಸುಗಳಿಗೆ ನಿಮ್ಮ ಹೊಲದ ಸ್ಥಿತಿ ನಮೂದಿಸಿ.",
    "env.cropType": "ಬೆಳೆ ಪ್ರಕಾರ",
    "env.selectCrop": "ಬೆಳೆ ಆಯ್ಕೆ",
    "env.wheat": "ಗೋಧಿ",
    "env.rice": "ಅಕ್ಕಿ",
    "env.corn": "ಜೋಳ",
    "env.sugarcane": "ಕಬ್ಬು",
    "env.cotton": "ಹತ್ತಿ",
    "env.vegetables": "ತರಕಾರಿಗಳು",
    "env.rainfall": "ಮಳೆ ಮಟ್ಟ",
    "env.selectLevel": "ಮಟ್ಟ ಆಯ್ಕೆ",
    "env.low": "ಕಡಿಮೆ",
    "env.moderate": "ಮಧ್ಯಮ",
    "env.heavy": "ಭಾರೀ",
    "env.wind": "ಗಾಳಿ ಒಡ್ಡುವಿಕೆ",
    "env.high": "ಹೆಚ್ಚು",
    "env.soil": "ಮಣ್ಣಿನ ಸ್ಥಿತಿ",
    "env.selectCondition": "ಸ್ಥಿತಿ ಆಯ್ಕೆ",
    "env.good": "ಉತ್ತಮ",
    "env.average": "ಸರಾಸರಿ",
    "env.poor": "ಕಳಪೆ",
    "env.fieldSize": "ಹೊಲದ ಗಾತ್ರ (ಎಕರೆ)",
    "env.analyzing": "ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    "env.predictRisk": "ಅಪಾಯ ಅಂದಾಜು",
    "result.severity": "ತೀವ್ರತೆ",
    "result.confidence": "ವಿಶ್ವಾಸ",
    "result.areaAffected": "ಪ್ರಭಾವಿತ ಪ್ರದೇಶ",
    "result.recommendations": "ಚೇತರಿಕೆ ಶಿಫಾರಸುಗಳು",
    "damage.safe": "ಯಾವುದೇ ಹಾನಿ ಇಲ್ಲ",
    "damage.animal_damage": "ಪ್ರಾಣಿ ಹಾನಿ ಪತ್ತೆ",
    "damage.crop_lodging": "ಬೆಳೆ ಬೀಳುವಿಕೆ ಪತ್ತೆ",
    "damage.combined": "ಸಂಯುಕ್ತ ಹಾನಿ ಪತ್ತೆ",
    "history.title": "ಸ್ಕ್ಯಾನ್ ಇತಿಹಾಸ",
    "history.scans": "ಸ್ಕ್ಯಾನ್‌ಗಳು",
    "history.scan": "ಸ್ಕ್ಯಾನ್",
    "history.clearAll": "ಎಲ್ಲಾ ತೆರವುಗೊಳಿಸಿ",
    "history.noScans": "ಇನ್ನೂ ಸ್ಕ್ಯಾನ್ ಇಲ್ಲ",
    "history.noScansDesc": "ಪ್ರಾರಂಭಿಸಲು ಬೆಳೆ ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಅಥವಾ ಪರಿಸರ ಡೇಟಾ ನಮೂದಿಸಿ.",
    "history.goToDashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಿ",
    "history.imageScan": "ಚಿತ್ರ ಸ್ಕ್ಯಾನ್",
    "history.environmental": "ಪರಿಸರ",
    "auth.welcomeBack": "ಮರಳಿ ಸ್ವಾಗತ",
    "auth.signInDesc": "ನಿಮ್ಮ ಖಾತೆಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ",
    "auth.email": "ಇಮೇಲ್",
    "auth.password": "ಪಾಸ್‌ವರ್ಡ್",
    "auth.forgotPassword": "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?",
    "auth.signInBtn": "ಸೈನ್ ಇನ್",
    "auth.noAccount": "ಖಾತೆ ಇಲ್ಲವೇ?",
    "auth.signUpLink": "ಸೈನ್ ಅಪ್",
    "auth.createAccount": "ನಿಮ್ಮ ಖಾತೆ ರಚಿಸಿ",
    "auth.createAccountDesc": "ಇಂದೇ ನಿಮ್ಮ ಬೆಳೆಗಳ ಮೇಲ್ವಿಚಾರಣೆ ಪ್ರಾರಂಭಿಸಿ",
    "auth.fullName": "ಪೂರ್ಣ ಹೆಸರು",
    "auth.createBtn": "ಖಾತೆ ರಚಿಸಿ",
    "auth.hasAccount": "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?",
    "auth.signInLink": "ಸೈನ್ ಇನ್",
    "auth.resetTitle": "ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ರೀಸೆಟ್ ಮಾಡಿ",
    "auth.resetDesc": "ನಾವು ನಿಮಗೆ ರೀಸೆಟ್ ಲಿಂಕ್ ಕಳುಹಿಸುತ್ತೇವೆ",
    "auth.checkEmail": "ನಿಮ್ಮ ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ",
    "auth.resetSent": "ನಾವು ಪಾಸ್‌ವರ್ಡ್ ರೀಸೆಟ್ ಲಿಂಕ್ ಕಳುಹಿಸಿದ್ದೇವೆ",
    "auth.sendResetLink": "ರೀಸೆಟ್ ಲಿಂಕ್ ಕಳುಹಿಸಿ",
    "auth.backToLogin": "ಲಾಗಿನ್‌ಗೆ ಹಿಂತಿರುಗಿ",
    "auth.setNewPassword": "ಹೊಸ ಪಾಸ್‌ವರ್ಡ್ ಸೆಟ್ ಮಾಡಿ",
    "auth.setNewPasswordDesc": "ಕೆಳಗೆ ನಿಮ್ಮ ಹೊಸ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ",
    "auth.newPassword": "ಹೊಸ ಪಾಸ್‌ವರ್ಡ್",
    "auth.updatePassword": "ಪಾಸ್‌ವರ್ಡ್ ಅಪ್‌ಡೇಟ್",
    "auth.verifyingLink": "ರೀಸೆಟ್ ಲಿಂಕ್ ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
    "auth.accountCreated": "ಖಾತೆ ರಚಿಸಲಾಗಿದೆ!",
    "auth.checkEmailVerify": "ಪರಿಶೀಲನಾ ಲಿಂಕ್‌ಗಾಗಿ ನಿಮ್ಮ ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ.",
    "auth.loginFailed": "ಲಾಗಿನ್ ವಿಫಲ",
    "auth.signupFailed": "ಸೈನ್ ಅಪ್ ವಿಫಲ",
    "auth.passwordUpdated": "ಪಾಸ್‌ವರ್ಡ್ ಅಪ್‌ಡೇಟ್ ಆಗಿದೆ!",
    "auth.passwordUpdatedDesc": "ಈಗ ನಿಮ್ಮ ಹೊಸ ಪಾಸ್‌ವರ್ಡ್‌ನಿಂದ ಸೈನ್ ಇನ್ ಮಾಡಬಹುದು.",
    "footer.text": "© 2026 CropGuard AI — ಸ್ಮಾರ್ಟ್ ಬೆಳೆ ಹಾನಿ ಪತ್ತೆ",
    "voice.notSupported": "ಭಾಷಣ ಬೆಂಬಲಿತವಾಗಿಲ್ಲ",
    "voice.notSupportedDesc": "ನಿಮ್ಮ ಬ್ರೌಸರ್ ಭಾಷಣ ಗುರುತಿಸುವಿಕೆಯನ್ನು ಬೆಂಬಲಿಸುವುದಿಲ್ಲ.",
    "voice.heard": "ನಾನು ಕೇಳಿದ್ದು:",
    "voice.goingUpload": "ಚಿತ್ರ ಅಪ್ಲೋಡ್ ವಿಭಾಗಕ್ಕೆ ಹೋಗುತ್ತಿದ್ದೇವೆ.",
    "voice.goingHistory": "ನಿಮ್ಮ ಸ್ಕ್ಯಾನ್ ಇತಿಹಾಸವನ್ನು ತೆರೆಯುತ್ತಿದ್ದೇವೆ.",
    "voice.goingEnvironment": "ಪರಿಸರ ಡೇಟಾ ವಿಭಾಗಕ್ಕೆ ಹೋಗುತ್ತಿದ್ದೇವೆ.",
    "voice.noResult": "ಇನ್ನೂ ವಿಶ್ಲೇಷಣೆ ಫಲಿತಾಂಶವಿಲ್ಲ. ದಯವಿಟ್ಟು ಮೊದಲು ಚಿತ್ರವನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ.",
    "voice.notUnderstood": "ಕ್ಷಮಿಸಿ, ನನಗೆ ಅರ್ಥವಾಗಲಿಲ್ಲ. ಅಪ್ಲೋಡ್, ಇತಿಹಾಸ ಅಥವಾ ವಿಶ್ಲೇಷಣೆ ಎಂದು ಹೇಳಿ.",
    "voice.error": "ಧ್ವನಿ ದೋಷ",
    "voice.stopReading": "ಓದುವುದನ್ನು ನಿಲ್ಲಿಸಿ",
    "voice.readResult": "ಫಲಿತಾಂಶ ಓದಿ",
    "voice.startListening": "ಧ್ವನಿ ಆದೇಶ ಪ್ರಾರಂಭಿಸಿ",
    "voice.stopListening": "ಕೇಳುವುದನ್ನು ನಿಲ್ಲಿಸಿ",
    "previous": "ಹಿಂದಿನ",
  },
  te: {
    "nav.upload": "అప్‌లోడ్",
    "nav.environment": "పర్యావరణం",
    "nav.history": "చరిత్ర",
    "nav.signIn": "సైన్ ఇన్",
    "nav.signOut": "సైన్ అవుట్",
    "hero.badge": "AI-ఆధారిత గుర్తింపు",
    "hero.title1": "పంట నష్టాన్ని గుర్తించండి",
    "hero.title2": "వ్యాపించడానికి ముందే.",
    "hero.subtitle": "మీ పొలం ఫోటో అప్‌లోడ్ చేయండి లేదా పర్యావరణ డేటా నమోదు చేయండి. జంతువుల నష్టం, పంట పడిపోవడం మరియు రికవరీ సిఫార్సుల కోసం తక్షణ AI విశ్లేషణ పొందండి.",
    "hero.uploadBtn": "చిత్రం అప్‌లోడ్",
    "hero.dataBtn": "డేటా నమోదు",
    "features.heading": "ఇది ఎలా పనిచేస్తుంది",
    "features.subheading": "రైతుల కోసం సరళమైన, శక్తివంతమైన సాధనాలు",
    "features.imageDetection": "చిత్ర గుర్తింపు",
    "features.imageDetectionDesc": "తక్షణ AI పంట నష్ట విశ్లేషణ కోసం ఫోటోలు అప్‌లోడ్ చేయండి",
    "features.severityEstimation": "తీవ్రత అంచనా",
    "features.severityEstimationDesc": "తక్కువ నుండి ఎక్కువ వరకు ఖచ్చితమైన నష్ట తీవ్రత స్థాయిలు పొందండి",
    "features.smartRecommendations": "స్మార్ట్ సిఫార్సులు",
    "features.smartRecommendationsDesc": "నష్ట రకం ఆధారంగా రికవరీ ప్రణాళికలు పొందండి",
    "features.riskAssessment": "ప్రమాద అంచనా",
    "features.riskAssessmentDesc": "అంచనా నష్ట విశ్లేషణ కోసం పర్యావరణ డేటా నమోదు చేయండి",
    "upload.heading": "చిత్ర విశ్లేషణ",
    "upload.subheading": "నష్టాన్ని గుర్తించడానికి, తీవ్రతను అంచనా వేయడానికి మరియు రికవరీ సిఫార్సులు పొందడానికి మీ పంట యొక్క స్పష్టమైన ఫోటో అప్‌లోడ్ చేయండి.",
    "upload.dropzone": "పంట చిత్రం అప్‌లోడ్",
    "upload.formats": "JPG, PNG, JPEG — డ్రాగ్ & డ్రాప్ లేదా ఎంచుకోవడానికి ట్యాప్ చేయండి",
    "upload.selectBtn": "ఫోటో ఎంచుకోండి",
    "upload.analyzing": "మీ పంట విశ్లేషించబడుతోంది...",
    "upload.reAnalyze": "మళ్ళీ విశ్లేషించు",
    "upload.complete": "విశ్లేషణ పూర్తయింది",
    "upload.failed": "విశ్లేషణ విఫలమైంది",
    "upload.invalidFile": "చెల్లని ఫైల్",
    "upload.invalidFileDesc": "దయచేసి చిత్ర ఫైల్ (JPG, PNG) అప్‌లోడ్ చేయండి.",
    "upload.healthyCrops": "ఆరోగ్యకరమైన పంటలు",
    "env.heading": "పర్యావరణ ప్రమాద అంచనా",
    "env.subheading": "నష్ట ప్రమాద అంచనా మరియు నివారణ సిఫార్సుల కోసం మీ పొలం పరిస్థితులను నమోదు చేయండి.",
    "env.cropType": "పంట రకం",
    "env.selectCrop": "పంట ఎంచుకోండి",
    "env.wheat": "గోధుమ",
    "env.rice": "బియ్యం",
    "env.corn": "మొక్కజొన్న",
    "env.sugarcane": "చెరకు",
    "env.cotton": "పత్తి",
    "env.vegetables": "కూరగాయలు",
    "env.rainfall": "వర్షపాత స్థాయి",
    "env.selectLevel": "స్థాయి ఎంచుకోండి",
    "env.low": "తక్కువ",
    "env.moderate": "మధ్యస్థం",
    "env.heavy": "భారీ",
    "env.wind": "గాలి బహిర్గతం",
    "env.high": "ఎక్కువ",
    "env.soil": "నేల పరిస్థితి",
    "env.selectCondition": "పరిస్థితి ఎంచుకోండి",
    "env.good": "మంచి",
    "env.average": "సగటు",
    "env.poor": "చెడ్డ",
    "env.fieldSize": "పొలం విస్తీర్ణం (ఎకరాలు)",
    "env.analyzing": "విశ్లేషిస్తోంది...",
    "env.predictRisk": "ప్రమాదం అంచనా",
    "result.severity": "తీవ్రత",
    "result.confidence": "విశ్వాసం",
    "result.areaAffected": "ప్రభావిత ప్రాంతం",
    "result.recommendations": "రికవరీ సిఫార్సులు",
    "damage.safe": "ఎటువంటి నష్టం లేదు",
    "damage.animal_damage": "జంతువుల నష్టం గుర్తించబడింది",
    "damage.crop_lodging": "పంట పడిపోవడం గుర్తించబడింది",
    "damage.combined": "మిశ్రమ నష్టం గుర్తించబడింది",
    "history.title": "స్కాన్ చరిత్ర",
    "history.scans": "స్కాన్‌లు",
    "history.scan": "స్కాన్",
    "history.clearAll": "అన్నీ తొలగించు",
    "history.noScans": "ఇంకా స్కాన్‌లు లేవు",
    "history.noScansDesc": "ప్రారంభించడానికి పంట చిత్రం అప్‌లోడ్ చేయండి లేదా పర్యావరణ డేటా నమోదు చేయండి.",
    "history.goToDashboard": "డాష్‌బోర్డ్‌కు వెళ్ళండి",
    "history.imageScan": "చిత్ర స్కాన్",
    "history.environmental": "పర్యావరణ",
    "auth.welcomeBack": "తిరిగి స్వాగతం",
    "auth.signInDesc": "మీ ఖాతాలో సైన్ ఇన్ చేయండి",
    "auth.email": "ఇమెయిల్",
    "auth.password": "పాస్‌వర్డ్",
    "auth.forgotPassword": "పాస్‌వర్డ్ మర్చిపోయారా?",
    "auth.signInBtn": "సైన్ ఇన్",
    "auth.noAccount": "ఖాతా లేదా?",
    "auth.signUpLink": "సైన్ అప్",
    "auth.createAccount": "మీ ఖాతా సృష్టించండి",
    "auth.createAccountDesc": "ఈ రోజే మీ పంటలను పర్యవేక్షించడం ప్రారంభించండి",
    "auth.fullName": "పూర్తి పేరు",
    "auth.createBtn": "ఖాతా సృష్టించు",
    "auth.hasAccount": "ఇప్పటికే ఖాతా ఉందా?",
    "auth.signInLink": "సైన్ ఇన్",
    "auth.resetTitle": "మీ పాస్‌వర్డ్ రీసెట్ చేయండి",
    "auth.resetDesc": "మేము మీకు రీసెట్ లింక్ పంపుతాము",
    "auth.checkEmail": "మీ ఇమెయిల్ చెక్ చేయండి",
    "auth.resetSent": "మేము పాస్‌వర్డ్ రీసెట్ లింక్ పంపాము",
    "auth.sendResetLink": "రీసెట్ లింక్ పంపు",
    "auth.backToLogin": "లాగిన్‌కు తిరిగి",
    "auth.setNewPassword": "కొత్త పాస్‌వర్డ్ సెట్ చేయండి",
    "auth.setNewPasswordDesc": "క్రింద మీ కొత్త పాస్‌వర్డ్ నమోదు చేయండి",
    "auth.newPassword": "కొత్త పాస్‌వర్డ్",
    "auth.updatePassword": "పాస్‌వర్డ్ అప్‌డేట్",
    "auth.verifyingLink": "రీసెట్ లింక్ ధృవీకరించబడుతోంది...",
    "auth.accountCreated": "ఖాతా సృష్టించబడింది!",
    "auth.checkEmailVerify": "ధృవీకరణ లింక్ కోసం మీ ఇమెయిల్ చెక్ చేయండి.",
    "auth.loginFailed": "లాగిన్ విఫలమైంది",
    "auth.signupFailed": "సైన్ అప్ విఫలమైంది",
    "auth.passwordUpdated": "పాస్‌వర్డ్ అప్‌డేట్ అయింది!",
    "auth.passwordUpdatedDesc": "ఇప్పుడు మీ కొత్త పాస్‌వర్డ్‌తో సైన్ ఇన్ చేయవచ్చు.",
    "footer.text": "© 2026 CropGuard AI — స్మార్ట్ పంట నష్ట గుర్తింపు",
    "voice.notSupported": "స్పీచ్ మద్దతు లేదు",
    "voice.notSupportedDesc": "మీ బ్రౌజర్ స్పీచ్ గుర్తింపును మద్దతు ఇవ్వదు.",
    "voice.heard": "నేను విన్నది:",
    "voice.goingUpload": "ఇమేజ్ అప్‌లోడ్ విభాగానికి వెళ్తున్నాము.",
    "voice.goingHistory": "మీ స్కాన్ చరిత్రను తెరుస్తున్నాము.",
    "voice.goingEnvironment": "పర్యావరణ డేటా విభాగానికి వెళ్తున్నాము.",
    "voice.noResult": "ఇంకా విశ్లేషణ ఫలితం లేదు. దయచేసి ముందుగా చిత్రాన్ని అప్‌లోడ్ చేయండి.",
    "voice.notUnderstood": "క్షమించండి, నాకు అర్థం కాలేదు. అప్‌లోడ్, చరిత్ర లేదా విశ్లేషణ అని చెప్పండి.",
    "voice.error": "వాయిస్ ఎర్రర్",
    "voice.stopReading": "చదవడం ఆపండి",
    "voice.readResult": "ఫలితం చదవండి",
    "voice.startListening": "వాయిస్ కమాండ్ ప్రారంభించండి",
    "voice.stopListening": "వినడం ఆపండి",
    "previous": "మునుపటి",
  },
  ta: {
    "nav.upload": "பதிவேற்றம்",
    "nav.environment": "சுற்றுச்சூழல்",
    "nav.history": "வரலாறு",
    "nav.signIn": "உள்நுழை",
    "nav.signOut": "வெளியேறு",
    "hero.badge": "AI-இயக்கப்படும் கண்டறிதல்",
    "hero.title1": "பயிர் சேதத்தைக் கண்டறியுங்கள்",
    "hero.title2": "பரவுவதற்கு முன்.",
    "hero.subtitle": "உங்கள் வயல் புகைப்படத்தை பதிவேற்றவும் அல்லது சுற்றுச்சூழல் தரவை உள்ளிடவும். விலங்கு சேதம், பயிர் சாய்வு மற்றும் மீட்பு பரிந்துரைகளுக்கு உடனடி AI பகுப்பாய்வு பெறுங்கள்.",
    "hero.uploadBtn": "படம் பதிவேற்றம்",
    "hero.dataBtn": "தரவு உள்ளிடு",
    "features.heading": "இது எப்படி வேலை செய்கிறது",
    "features.subheading": "விவசாயிகளுக்கான எளிய, சக்திவாய்ந்த கருவிகள்",
    "features.imageDetection": "பட கண்டறிதல்",
    "features.imageDetectionDesc": "உடனடி AI பயிர் சேத பகுப்பாய்வுக்கு புகைப்படங்களை பதிவேற்றவும்",
    "features.severityEstimation": "தீவிரம் மதிப்பீடு",
    "features.severityEstimationDesc": "குறைவு முதல் அதிகம் வரை துல்லியமான சேத தீவிர நிலைகள் பெறுங்கள்",
    "features.smartRecommendations": "ஸ்மார்ட் பரிந்துரைகள்",
    "features.smartRecommendationsDesc": "சேத வகையின் அடிப்படையில் மீட்பு திட்டங்களைப் பெறுங்கள்",
    "features.riskAssessment": "ஆபத்து மதிப்பீடு",
    "features.riskAssessmentDesc": "முன்கணிப்பு சேத பகுப்பாய்வுக்கு சுற்றுச்சூழல் தரவை உள்ளிடவும்",
    "upload.heading": "பட பகுப்பாய்வு",
    "upload.subheading": "சேதத்தைக் கண்டறிய, தீவிரத்தை மதிப்பிட மற்றும் மீட்பு பரிந்துரைகளைப் பெற உங்கள் பயிரின் தெளிவான புகைப்படத்தை பதிவேற்றவும்.",
    "upload.dropzone": "பயிர் படம் பதிவேற்றம்",
    "upload.formats": "JPG, PNG, JPEG — இழுத்து விடவும் அல்லது தேர்வு செய்ய தட்டவும்",
    "upload.selectBtn": "புகைப்படம் தேர்வு",
    "upload.analyzing": "உங்கள் பயிர் பகுப்பாய்வு செய்யப்படுகிறது...",
    "upload.reAnalyze": "மறு பகுப்பாய்வு",
    "upload.complete": "பகுப்பாய்வு முடிந்தது",
    "upload.failed": "பகுப்பாய்வு தோல்வி",
    "upload.invalidFile": "தவறான கோப்பு",
    "upload.invalidFileDesc": "தயவுசெய்து பட கோப்பை (JPG, PNG) பதிவேற்றவும்.",
    "upload.healthyCrops": "ஆரோக்கியமான பயிர்கள்",
    "env.heading": "சுற்றுச்சூழல் ஆபத்து மதிப்பீடு",
    "env.subheading": "சேத ஆபத்து முன்கணிப்பு மற்றும் தடுப்பு பரிந்துரைகளுக்கு உங்கள் வயல் நிலைமைகளை உள்ளிடவும்.",
    "env.cropType": "பயிர் வகை",
    "env.selectCrop": "பயிர் தேர்வு",
    "env.wheat": "கோதுமை",
    "env.rice": "அரிசி",
    "env.corn": "மக்காச்சோளம்",
    "env.sugarcane": "கரும்பு",
    "env.cotton": "பருத்தி",
    "env.vegetables": "காய்கறிகள்",
    "env.rainfall": "மழை அளவு",
    "env.selectLevel": "அளவு தேர்வு",
    "env.low": "குறைவு",
    "env.moderate": "மிதமான",
    "env.heavy": "கடும்",
    "env.wind": "காற்று வெளிப்பாடு",
    "env.high": "அதிகம்",
    "env.soil": "மண் நிலை",
    "env.selectCondition": "நிலை தேர்வு",
    "env.good": "நல்ல",
    "env.average": "சராசரி",
    "env.poor": "மோசம்",
    "env.fieldSize": "வயல் அளவு (ஏக்கர்)",
    "env.analyzing": "பகுப்பாய்வு செய்கிறது...",
    "env.predictRisk": "ஆபத்தை கணிக்க",
    "result.severity": "தீவிரம்",
    "result.confidence": "நம்பிக்கை",
    "result.areaAffected": "பாதிக்கப்பட்ட பகுதி",
    "result.recommendations": "மீட்பு பரிந்துரைகள்",
    "damage.safe": "எந்த சேதமும் இல்லை",
    "damage.animal_damage": "விலங்கு சேதம் கண்டறியப்பட்டது",
    "damage.crop_lodging": "பயிர் சாய்வு கண்டறியப்பட்டது",
    "damage.combined": "கலப்பு சேதம் கண்டறியப்பட்டது",
    "history.title": "ஸ்கேன் வரலாறு",
    "history.scans": "ஸ்கேன்கள்",
    "history.scan": "ஸ்கேன்",
    "history.clearAll": "அனைத்தும் நீக்கு",
    "history.noScans": "இதுவரை ஸ்கேன்கள் இல்லை",
    "history.noScansDesc": "தொடங்க பயிர் படம் பதிவேற்றவும் அல்லது சுற்றுச்சூழல் தரவை உள்ளிடவும்.",
    "history.goToDashboard": "டாஷ்போர்டுக்கு செல்",
    "history.imageScan": "பட ஸ்கேன்",
    "history.environmental": "சுற்றுச்சூழல்",
    "auth.welcomeBack": "மீண்டும் வருக",
    "auth.signInDesc": "உங்கள் கணக்கில் உள்நுழையுங்கள்",
    "auth.email": "மின்னஞ்சல்",
    "auth.password": "கடவுச்சொல்",
    "auth.forgotPassword": "கடவுச்சொல் மறந்துவிட்டதா?",
    "auth.signInBtn": "உள்நுழை",
    "auth.noAccount": "கணக்கு இல்லையா?",
    "auth.signUpLink": "பதிவு செய்",
    "auth.createAccount": "உங்கள் கணக்கை உருவாக்கு",
    "auth.createAccountDesc": "இன்றே உங்கள் பயிர்களை கண்காணிக்க தொடங்கு",
    "auth.fullName": "முழு பெயர்",
    "auth.createBtn": "கணக்கு உருவாக்கு",
    "auth.hasAccount": "ஏற்கனவே கணக்கு உள்ளதா?",
    "auth.signInLink": "உள்நுழை",
    "auth.resetTitle": "கடவுச்சொல்லை மீட்டமை",
    "auth.resetDesc": "மீட்டமைப்பு இணைப்பை அனுப்புவோம்",
    "auth.checkEmail": "உங்கள் மின்னஞ்சலை சரிபாருங்கள்",
    "auth.resetSent": "கடவுச்சொல் மீட்டமைப்பு இணைப்பை அனுப்பியுள்ளோம்",
    "auth.sendResetLink": "மீட்டமைப்பு இணைப்பு அனுப்பு",
    "auth.backToLogin": "உள்நுழைவுக்கு திரும்பு",
    "auth.setNewPassword": "புதிய கடவுச்சொல் அமை",
    "auth.setNewPasswordDesc": "கீழே உங்கள் புதிய கடவுச்சொல்லை உள்ளிடவும்",
    "auth.newPassword": "புதிய கடவுச்சொல்",
    "auth.updatePassword": "கடவுச்சொல் புதுப்பி",
    "auth.verifyingLink": "மீட்டமைப்பு இணைப்பு சரிபார்க்கப்படுகிறது...",
    "auth.accountCreated": "கணக்கு உருவாக்கப்பட்டது!",
    "auth.checkEmailVerify": "சரிபார்ப்பு இணைப்புக்கு உங்கள் மின்னஞ்சலை சரிபாருங்கள்.",
    "auth.loginFailed": "உள்நுழைவு தோல்வி",
    "auth.signupFailed": "பதிவு தோல்வி",
    "auth.passwordUpdated": "கடவுச்சொல் புதுப்பிக்கப்பட்டது!",
    "auth.passwordUpdatedDesc": "இப்போது உங்கள் புதிய கடவுச்சொல்லுடன் உள்நுழையலாம்.",
    "footer.text": "© 2026 CropGuard AI — ஸ்மார்ட் பயிர் சேத கண்டறிதல்",
    "voice.notSupported": "பேச்சு ஆதரிக்கப்படவில்லை",
    "voice.notSupportedDesc": "உங்கள் உலாவி பேச்சு அங்கீகாரத்தை ஆதரிக்காது.",
    "voice.heard": "நான் கேட்டது:",
    "voice.goingUpload": "படம் பதிவேற்றம் பகுதிக்கு செல்கிறோம்.",
    "voice.goingHistory": "உங்கள் ஸ்கேன் வரலாற்றை திறக்கிறோம்.",
    "voice.goingEnvironment": "சுற்றுச்சூழல் தரவு பகுதிக்கு செல்கிறோம்.",
    "voice.noResult": "இன்னும் பகுப்பாய்வு முடிவு இல்லை. முதலில் படத்தை பதிவேற்றவும்.",
    "voice.notUnderstood": "மன்னிக்கவும், புரியவில்லை. பதிவேற்றம், வரலாறு அல்லது பகுப்பாய்வு என்று சொல்லுங்கள்.",
    "voice.error": "குரல் பிழை",
    "voice.stopReading": "படிப்பதை நிறுத்து",
    "voice.readResult": "முடிவைப் படி",
    "voice.startListening": "குரல் கட்டளையை தொடங்கு",
    "voice.stopListening": "கேட்பதை நிறுத்து",
    "previous": "முந்தைய",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("cropguard-lang");
    return (saved as Language) || "en";
  });

  const handleSetLanguage = useCallback((lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("cropguard-lang", lang);
  }, []);

  const t = useCallback(
    (key: string) => translations[language]?.[key] || translations.en[key] || key,
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
